<a href="https://colab.research.google.com/github/kimgoinghard/study-machine-learning/blob/main/study_torch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import torch

In [2]:
t = np.array([[ [0,1,2],
                [3,4,5]],
                [[6,7,8],
                 [9,10,11]]
])

In [10]:
t.ndim
t.shape
t.size

12

In [13]:
ft = torch.FloatTensor(t) # numpy array를 tensor로 변경

In [14]:
ft.shape #2x2x3 

torch.Size([2, 2, 3])

##View
- 원소의 수를 유지하며 텐서의 크기를 변경

In [15]:
print(ft.view([-1,3])) #ft tensor를 (?, 3)의 크기로 변경.  -1은 파이토치에 맡기겠다는 의미. 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


In [20]:
print(ft.view([-1,3]).shape) #4x3의 크기를 가지게 됨.

torch.Size([4, 3])


In [22]:
print(ft.view([-1,1,3])) #(?,1,3)의 크기로 만들어 줌.
print(ft.view([-1,1,3]).shape) # 4x1x3

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


##Squeeze
- 1인 차원을 제거

In [25]:
 ft = torch.FloatTensor([[0], [1], [2]])
 print(ft)
 print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [29]:
print(ft.squeeze()) #(3,1) 에서 (3,)으로 바뀜.
print(ft.squeeze().shape) 

tensor([0., 1., 2.])
torch.Size([3])


##Unsqueeze
-  특정 위치에 1인 차원 추가


In [31]:
ft = torch.FloatTensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [33]:
print(ft.unsqueeze(0)) #첫번째 차원에 1인 차원이 추가됨.
print(ft.unsqueeze(0).shape) # 크기가 3인 벡터가 (1,3)의 2차원 텐서로 변경됨.

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [35]:
print(ft.unsqueeze(1)) #두번째 차원에 1인 차원 추가
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [37]:
print(ft.unsqueeze(-1)) #-1은 마지막 인덱스를 의미하므로 (3,) 였던 벡터에 1인 차원이 추가됨.
print(ft.unsqueeze(-1).shape) #(3,1)로 바뀜..

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


view(), squeeze(), unsqueeze() 는 공통적으로 원소의 수를 그대로 유지하며 텐서의 모양과 차원을 변경한다.

##Type Casting

In [40]:
lt = torch.LongTensor([1,2,3,4]) #long 타입의 텐서
print(lt) 

tensor([1, 2, 3, 4])


In [42]:
#long -> float
print(lt.float()) 

tensor([1., 2., 3., 4.])


In [44]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [46]:
#byte -> long, float
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


#연결하기 : Concatenate(Cat)


In [47]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [52]:
print(torch.cat([x,y],dim = 0)) #첫번째 차원으로 연결하기, 즉 행으로 이어붙이기
print(torch.cat([x,y],dim = 1)) #열로 이어붙이기. /  열로 추가.

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


#Stacking(쌓기)

In [53]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [57]:
print(torch.stack([x,y,z])) # dim = 0
print(torch.stack([x,y,z], dim = 1)) #두번째 차원이 증가하도록 스택킹

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


x,y,z는 모두 (2,) 크기 였음. 이를 unsqueez(0)을 하여 (1,2) (열벡터)가 됨. 이를 다시 cat(dim0=) 하여 스택킹 과정이 이루어지는 것임. 

In [58]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [59]:
print(torch.ones_like(x)) #모양이 x와 같고 1로 값이 채워진 텐서 생성

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [60]:
print(torch.zeros_like(x)) #모양이 x와 같고 0으로 값이 채워진 텐서 

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [61]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [63]:
print(x.mul(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [66]:
print(x.mul_(2)) #연산뒤에 '_'를 넣어주면 덮어쓰기 연산이 이루어짐.
print(x)

tensor([[ 8., 16.],
        [24., 32.]])
tensor([[ 8., 16.],
        [24., 32.]])
