<a href="https://colab.research.google.com/github/kimgoinghard/study-machine-learning/blob/main/study_pytorch_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [17]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [20]:
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

Rank of t :  1
Shape of t :  (7,)


In [22]:
t = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9. ],
              [10., 11., 12.]
              ])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [25]:
print(t.ndim) #차원을 출력. 1차원은 벡터, 2차원은 행렬, 3차원은 3차원 텐서
print(t.shape) # 크기를 출력 4X3이라는 뜻.

2
(4, 3)


In [27]:
import torch

In [32]:
t  = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [37]:
print(t.dim()) #차원
print(t.shape) #크기
print(t.size()) #크기

1
torch.Size([7])
torch.Size([7])


In [42]:
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])


In [45]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10.,11.,12.]])

In [50]:
print(t.dim()) #차원
print(t.size()) #크기

2
torch.Size([4, 3])


In [60]:
t[2 , :]
t[:, 1]

tensor([ 2.,  5.,  8., 11.])

In [63]:
 m1  = torch.FloatTensor( [ [3,2] ] )
 m2  = torch.FloatTensor( [ [2,2 ] ] )
print(m1+m2) 

tensor([[5., 4.]])


In [66]:
m1 = torch.FloatTensor( [ [ 1, 2 ] ] )
m2 = torch.FloatTensor([3])
print(m1+m2)

tensor([[4., 5.]])


In [73]:
m1 = torch.FloatTensor([ [1,2],[3,4] ])
m2 = torch.FloatTensor([[2],[1]])
print(m1.shape) # 2X2
print(m2.shape) # 2X1
m1.matmul(m2) #  m1xm2

torch.Size([2, 2])
torch.Size([2, 1])


tensor([[ 4.],
        [10.]])

In [74]:
print(m1*m2) #행렬곱과 곱셈(element-wise)에는 차이가 있다. 

tensor([[2., 4.],
        [3., 4.]])


In [79]:
t =torch.FloatTensor([1,2])
t.mean()
t.var()

tensor(0.5000)

In [84]:
t = torch.FloatTensor([ [1., 2. ],[3., 4.] ])
t.mean()
t.mean(dim=0) #0차원 기준 즉 행으로 평균
t.mean(dim=1) #열로 평균

tensor([1.5000, 3.5000])

In [87]:
tt = torch.FloatTensor([ [1., 2. ],[3., 4.] ])
tt.max()
tt.max(dim=0) #첫번째 차원을 제거한다는 의미 (2,2) 텐서에서 (1,2)가 된다. -> 따라서 행기준 최댓값과 그에 해당하는 인덱스를 출력한다. 

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

데이터사이언스 분야에서 3차원 이상의 텐서는 다차원 행렬, 배열로 간주할 수 있음. 그리고 주로 3차원 이상을 텐서라고 하지만 벡터를 1차원 텐서라고 표현하기도 함

훈련 데이터 하나의 크기가 256이라고 한다면, [2,3,6,...., ]의 길이가 256이라고 생각하면 됨. 

훈련데이터 한개 = 벡터의 차원 = 256  

이런 훈련데이터가 3000개 있다면 전체 훈련데이터의 크기는 3000x256 이 되고, 이는 2차원 텐서임. 

컴퓨터가 이를 1개씩 처리할 수 도있겠지만 시간이 오래걸리고 효율이 낮음. 그래서 보통 덩어리로 처리함. 3000개 중 64개씩 꺼내 처리한다고 하면 이때 batch-size가 64인 것. 그리고 이 때 컴퓨터가 한 번에 처리하는 2차원 텐서의 크기는 64x256

텐서의 표기는 (2,3) 과 2x3은 같은 것. 주의할 점은 (2, )은 1x2라는 것.

