<a href="https://colab.research.google.com/github/kimgoinghard/study-machine-learning/blob/main/study_torch_12_xor_problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#퍼셉트론(Perceptron)
- 퍼셉트론은 초기 형태의 인공 신경망으로 다수의 입력으로부터 하나의 결과를 내는 알고리즘.

In [8]:
import torch
import torch.nn as nn

In [4]:
device = 'cuda' if torch.cuda.is_available() else 'cpu' #gpu연산이 가능한 경우엔 gpu연산을 할 수 있도록 설정해준다. 
torch.manual_seed(777)
if device == 'cuda':
  torch.cuda.manual_seed_all(777)

In [6]:
X = torch.FloatTensor([[0,0], [0,1], [1,0], [1,1] ]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

In [9]:
linear = nn.Linear(2, 1, bias=True) #linear 층 
sigmoid = nn.Sigmoid() #시그모이드 층 
model = nn.Sequential(linear, sigmoid).to(device) #nn.Sequential()로 linear, sigmoid 를 쌓은 계층 만들고 model 객체에 저장하고 gpu에서 시작.

In [11]:
criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr = 1)

In [13]:
for step in range(10001):
  optimizer.zero_grad()
  hypo = model(X)

  cost = criterion(hypo, Y)
  cost.backward()
  optimizer.step()

  if step % 100 == 0:
    print(step, cost.item())

0 0.6931471824645996
100 0.6931471824645996
200 0.6931471824645996
300 0.6931471824645996
400 0.6931471824645996
500 0.6931471824645996
600 0.6931471824645996
700 0.6931471824645996
800 0.6931471824645996
900 0.6931471824645996
1000 0.6931471824645996
1100 0.6931471824645996
1200 0.6931471824645996
1300 0.6931471824645996
1400 0.6931471824645996
1500 0.6931471824645996
1600 0.6931471824645996
1700 0.6931471824645996
1800 0.6931471824645996
1900 0.6931471824645996
2000 0.6931471824645996
2100 0.6931471824645996
2200 0.6931471824645996
2300 0.6931471824645996
2400 0.6931471824645996
2500 0.6931471824645996
2600 0.6931471824645996
2700 0.6931471824645996
2800 0.6931471824645996
2900 0.6931471824645996
3000 0.6931471824645996
3100 0.6931471824645996
3200 0.6931471824645996
3300 0.6931471824645996
3400 0.6931471824645996
3500 0.6931471824645996
3600 0.6931471824645996
3700 0.6931471824645996
3800 0.6931471824645996
3900 0.6931471824645996
4000 0.6931471824645996
4100 0.6931471824645996
4200

In [34]:
with torch.no_grad():
  hypo = model(X)
  predicted = (hypo > 0.5).float()
  accuracy = (predicted == Y).float().mean()
  print('모델의 출력값 : \n ', hypo.detach().cpu().numpy())
  print('모델의 예측값 : \n', predicted.detach().cpu().numpy())
  print('실제값(Y) : \n', Y.cpu().numpy())
  print('정확도(Accuracy) : ', accuracy.item())

모델의 출력값 : 
  [[1.1168801e-04]
 [9.9982882e-01]
 [9.9984229e-01]
 [1.8529482e-04]]
모델의 예측값 : 
 [[0.]
 [1.]
 [1.]
 [0.]]
실제값(Y) : 
 [[0.]
 [1.]
 [1.]
 [0.]]
정확도(Accuracy) :  1.0


단층 퍼셉트론은 XOR문제를 풀지 못하는 모습을 볼 수있다. 

In [16]:
import torch
import torch.nn as nn

In [19]:
device = 'cuda' if torch.cuda.is_available() else 'cpu' #gpu사용 설정

torch.manual_seed(777)
if device == 'cuda':
  torch.cuda.manual_seed_all(777)

In [20]:
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device) #gpu에서 계산한다.
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

In [21]:
model = nn.Sequential(
    nn.Linear(2,10, bias = True), #input_layer = 2, hidden_layer = 10
    nn.Sigmoid(),
    nn.Linear(10,10, bias = True), # 10 x 10
    nn.Sigmoid(),
    nn.Linear(10,10, bias = True), # 10 x 10
    nn.Sigmoid(),
    nn.Linear(10,1, bias = True), # 10 x 1
    nn.Sigmoid()
).to(device)

In [23]:
criterion = torch.nn.BCELoss().to(device) #이진분류에서 사용하는 크로스엔트로피 함수이다.
optimizer = torch.optim.SGD(model.parameters(), lr = 1)  #학습률 : 1

In [24]:
for epoch in range(10001):
  optimizer.zero_grad()
  #forward
  hypo = model(X)

  cost = criterion(hypo, Y)
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print(epoch, cost.item())


#모델 학습시키기.

0 0.6948983669281006
100 0.693155825138092
200 0.6931535601615906
300 0.6931513547897339
400 0.6931493282318115
500 0.6931473016738892
600 0.6931453943252563
700 0.6931434869766235
800 0.6931416988372803
900 0.6931397914886475
1000 0.6931379437446594
1100 0.6931361556053162
1200 0.6931343078613281
1300 0.6931324005126953
1400 0.6931304931640625
1500 0.6931284666061401
1600 0.6931264400482178
1700 0.6931242942810059
1800 0.6931220293045044
1900 0.6931197047233582
2000 0.6931172013282776
2100 0.6931145191192627
2200 0.6931115984916687
2300 0.6931084990501404
2400 0.6931051015853882
2500 0.6931014657020569
2600 0.6930974721908569
2700 0.6930930018424988
2800 0.6930879950523376
2900 0.6930825114250183
3000 0.6930762529373169
3100 0.6930692195892334
3200 0.6930611729621887
3300 0.6930519342422485
3400 0.6930411458015442
3500 0.6930283904075623
3600 0.6930132508277893
3700 0.6929951310157776
3800 0.6929728984832764
3900 0.6929452419281006
4000 0.6929103136062622
4100 0.6928649544715881
4200 

In [33]:
with torch.no_grad():
  hypo = model(X)
  predicted = (hypo > 0.5).float()
  accuracy = (predicted == Y).float().mean()
  print('모델의 출력값(Hypothesis): \n ', hypo.detach().cpu().numpy())
  print('모델의 예측값(Predicted): \n ', predicted.detach().cpu().numpy())
  print('실제값(Y): \n', Y.cpu().numpy())
  print('정확도(Accuracy): ', accuracy.item())

#다층 퍼셉트론을 이용한 결과 올바르게 예측하였다.
# detach()는 이 연산 기록으로 부터 분리한 tensor을 반환 -> 해당텐서가 더 이상 그래디언트를 계산할 필요가 없으며 역전파를 위한 추가 계산에 참여하지 않게 된다.
# GPU 메모리에 올려져 있는 tensor를 cpu 메모리로 복사하는 method
#tensor를 numpy로 변환하여 반환. 이때 저장공간을 공유하기 때문에 하나를 변경하면 다른 하나도 변경된다.



모델의 출력값(Hypothesis): 
  [[1.1168801e-04]
 [9.9982882e-01]
 [9.9984229e-01]
 [1.8529482e-04]]
모델의 예측값(Predicted): 
  [[0.]
 [1.]
 [1.]
 [0.]]
실제값(Y): 
 [[0.]
 [1.]
 [1.]
 [0.]]
정확도(Accuracy):  1.0
