<a href="https://colab.research.google.com/github/kimgoinghard/study-machine-learning/blob/main/studt_torch_5_nn_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
torch.manual_seed(1) #랜덤시드 설정

In [4]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [5]:
model = nn.Linear(1,1) #nn.Linear()는 입력, 출력의 차원을 인수로 받는다.

In [6]:
print(list(model.parameters())) #랜덤으로 초기화되어있는 모습. 학습해야 할 매개변수 이므로 requires_grad = True인 모습.

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [8]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01) #model.parameters() 를 통해서 매개변수를 전달

In [9]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train) #model은 nn.Linear객체

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [15]:
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var)
print(pred_y)

tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [16]:
print(list(model.parameters())) #W = 2, b = 0으로 매개변수가 학습되었다. 

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [19]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])
print(x_train.shape)

torch.Size([5, 3])


In [20]:
model = nn.Linear(3,1) #다중선형회귀 진행 시 x*%*W + b 이고, x의 차원이 5x3 이므로 w는 3x1

In [22]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1188,  0.2937,  0.0803]], requires_grad=True), Parameter containing:
tensor([-0.0707], requires_grad=True)]


In [23]:
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5) #lr = 0.01로 해본 결과 기울기가 발산하게 됨.

In [28]:
n_epoch = 2000
for epoch in range(n_epoch+1):
  
  #y_hat 계산
  prediction = model(x_train)

  #비용함수 정의
  cost = F.mse_loss(prediction, y_train) #평균제곱오차함수

  optimizer.zero_grad() #0으로 초기화

  cost.backward() #비용함수 미분해 기울기 계산

  optimizer.step() #매개변수 갱신

  if epoch%100 ==0:
    print('Epoch : {0} / {1}  Cost : {2:.6f}'.format(epoch, n_epoch,cost.item()))

Epoch : 0 / 2000  Cost : 0.515876
Epoch : 100 / 2000  Cost : 0.505210
Epoch : 200 / 2000  Cost : 0.495069
Epoch : 300 / 2000  Cost : 0.485425
Epoch : 400 / 2000  Cost : 0.476255
Epoch : 500 / 2000  Cost : 0.467531
Epoch : 600 / 2000  Cost : 0.459224
Epoch : 700 / 2000  Cost : 0.451330
Epoch : 800 / 2000  Cost : 0.443804
Epoch : 900 / 2000  Cost : 0.436651
Epoch : 1000 / 2000  Cost : 0.429832
Epoch : 1100 / 2000  Cost : 0.423336
Epoch : 1200 / 2000  Cost : 0.417150
Epoch : 1300 / 2000  Cost : 0.411262
Epoch : 1400 / 2000  Cost : 0.405632
Epoch : 1500 / 2000  Cost : 0.400277
Epoch : 1600 / 2000  Cost : 0.395171
Epoch : 1700 / 2000  Cost : 0.390292
Epoch : 1800 / 2000  Cost : 0.385643
Epoch : 1900 / 2000  Cost : 0.381191
Epoch : 2000 / 2000  Cost : 0.376956


In [30]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)  #실제값이 152였음

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.5478]], grad_fn=<AddmmBackward0>)


In [34]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.8304, 0.4868, 0.6938]], requires_grad=True), Parameter containing:
tensor([-0.0520], requires_grad=True)]
